const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const source=fs.readFileSync(path.join(__dirname,'../editing-intake-maintenance.js'),'utf8');
function fixture(flag=false,status=200){const nodes=Object.fromEntries(['notice','login','health','prepare'].map(k=>[k,{}]));let listener;const calls=[];const auth={onAuthStateChanged(fn){listener=fn;return()=>{};},async signInWithPopup(){calls.push('login');}};const box={AbortController,Error,firebase:{auth:{GoogleAuthProvider:function(){}}}};vm.runInNewContext(source,box);box.EditingIntakeMaintenance.mount({auth,document:{getElementById:k=>nodes[k]},fetchImpl:async(url,options)=>{calls.push({url,options});return{ok:status===200,status,json:async()=>url.endsWith('/config')?{driveRootProvisionAvailable:flag}:url.endsWith('/health')?{connectionVerified:true,canAddChildren:true,broadAccess:false}:{rootFolderId:'fixture-root'}};}});return{nodes,calls,auth:next=>listener(next)};}
const owner={getIdToken:async()=> 'FIXTURE_ONLY'};
test('unauthenticated page hides actions and uses ordinary popup login',async()=>{const f=fixture();await f.auth(null);assert.equal(f.nodes.prepare.hidden,true);assert.equal(f.nodes.health.hidden,true);await f.nodes.login.onclick();assert.deepEqual(f.calls,['login']);});
test('flag false hides preparation and rejects direct handler without POST',async()=>{const f=fixture();await f.auth(owner);assert.equal(f.nodes.prepare.hidden,true);await f.nodes.prepare.onclick();assert.equal(f.calls.length,1);});
test('verified server config enables only fixed empty POST using bearer and omit',async()=>{const f=fixture(true);await f.auth(owner);await f.nodes.prepare.onclick();const c=f.calls[1];assert.equal(c.url,'https://mono-editing-intake.mono-create-group.workers.dev/api/internal-admin/maintenance/drive-root');assert.equal(c.options.body,'{}');assert.equal(c.options.credentials,'omit');assert.equal(c.options.headers.Authorization,'Bearer FIXTURE_ONLY');assert.match(f.nodes.notice.textContent,/fixture-root/);});
for(const status of [401,403])test('server rejection '+status+' never enables prepare',async()=>{const f=fixture(true,status);await f.auth(owner);assert.equal(f.nodes.prepare.hidden,true);await f.nodes.prepare.onclick();assert.equal(f.calls.length,1);});
test('auth change clears permission and prevents old token request',async()=>{const f=fixture(true);let resolve;const pending=f.auth({getIdToken:()=>new Promise(r=>resolve=r)});await f.auth(null);resolve('STALE');await pending;assert.equal(f.calls.length,0);assert.equal(f.nodes.prepare.hidden,true);});
test('no Firestore or business-storage operations, matching Firebase configuration',()=>{const html=fs.readFileSync(path.join(__dirname,'../editing-intake-maintenance.html'),'utf8'),index=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8');assert.doesNotMatch(source+html,/firebase-firestore|firebase\.firestore|localStorage|sessionStorage|\/orders|\/commands/);assert.equal(html.match(/firebase.initializeApp\((\{[\s\S]*?\})\);/)[1],index.match(/firebase.initializeApp\((\{[\s\S]*?\})\);/)[1]);});
