const assert=require('assert'),fs=require('fs'),vm=require('vm');
const source=fs.readFileSync(require('path').join(__dirname,'..','feedback-workflow.js'),'utf8');
const sandbox={window:{},console,sessionStorage:{getItem(){return null},setItem(){},removeItem(){}},Date,Math};sandbox.window.window=sandbox.window;
vm.runInNewContext(source,sandbox);
const api=sandbox.window.FeedbackWorkflow,t=api._test;
assert.equal(t.isCorrection({status:'修正中'}),true);
assert.equal(t.isCorrection({correctionReason:'冒頭を短く'}),true);
assert.equal(t.isCorrection({status:'編集者進行中'}),false);
const row=t.normalize('one',{portalUid:'u1',editorUid:'u1',learning:'  学び  ',status:'bad'});
assert.equal(row.learning,'学び');assert.equal(row.status,'submitted');
const job={id:'j1',parentCaseId:'p1',workflow:{round:2},correctionReason:'修正'};
api.configure({user:{uid:'u1'}});
const a=t.feedbackId(job,{nonce:'x'}),b=t.feedbackId(job,{nonce:'x'}),c=t.feedbackId(job,{nonce:'y'});
assert.equal(a,b);assert.notEqual(a,c);assert.ok(a.startsWith('fb_'));
assert.equal(t.manualId({portalUid:'u1',id:'fb_123'}),'feedback_u1_fb_123');
api.configure({access:{roles:['動画編集ディレクター']},getPortalUids:()=>['u1']});
assert.equal(t.canSee({portalUid:'u1'}),true);assert.equal(t.canSee({portalUid:'u2'}),false);
assert.deepEqual(Array.from(t.managerPortalUids()),['u1']);
assert.equal(source.includes("collectionGroup('feedback')"),false,'manager reads must use concrete authorized portal paths');
assert.equal(source.includes("console.warn('feedback manager read'"),false,'predictable manager read denials must not create console noise');
assert.ok(source.includes('managerScopeKey'),'manager listener scope is refreshed after portal access loads');
assert.ok(source.includes("state.managerRows=[];state.managerReadError='';"),'scope changes immediately remove stale manager rows');
assert.ok(source.includes("listenerError('manager',e,uid)"),'permission errors retain their originating portal scope');
assert.ok(source.includes("permissionDenied&&!managerPortalUids().includes(String(uid))"),'only revoked scopes suppress permission-denied');
assert.ok(source.includes('state.managerReadError?'), 'unexpected manager read failures are actionable in the page');
assert.ok(source.includes('state.editorReadError?'), 'unexpected editor read failures are actionable in the page');
const editorSource=fs.readFileSync(require('path').join(__dirname,'..','editor-features.js'),'utf8');
const editorHtml=fs.readFileSync(require('path').join(__dirname,'..','editor.html'),'utf8');
assert.ok(editorHtml.includes('feedback-workflow.js'), 'editor portal loads the dedicated feedback module');
assert.ok(editorSource.includes("['feedback','過去フィードバック']"), 'feedback appears in editor navigation');
assert.ok(editorSource.includes("view==='feedback'"), 'feedback has a dedicated editor route');
assert.ok(editorSource.includes('openEditorFeedback'), 'revision job opens the dedicated feedback route');
assert.equal(editorSource.includes('submitFeedbackNote='),false, 'legacy chat feedback submit handler is removed');
assert.equal(editorSource.includes('saveFeedbackDraft='),false, 'legacy chat feedback draft handler is removed');
console.log('feedback-workflow logic tests passed');
